name: "build"
on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install cross-compilation deps
        run: |
          sudo apt update
          sudo apt install gcc-aarch64-linux-gnu
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            extra-platforms = aarch64-linux
            max-jobs = auto
      - run: |
          nix build --print-build-logs --show-trace
